######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 9 15:07:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include
OBJECTS_DIR = obj
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += include/EZkey.hpp include/EZpiano.hpp include/EZpianoview.hpp
SOURCES += src/EZkey.cpp src/EZpiano.cpp src/EZzic.cpp src/EZpianoview.cpp
