#############################################################################
# Makefile for building: EZzik
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Mar 16 14:29:00 2016
# Project:  EZzik.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile EZzik.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/EZfiledialog.cpp \
		src/EZkey.cpp \
		src/EZnote.cpp \
		src/EZnotenames.cpp \
		src/EZnotenamesview.cpp \
		src/EZpiano.cpp \
		src/EZpianoview.cpp \
		src/EZreset.cpp \
		src/EZscore.cpp \
		src/EZscoreview.cpp \
		src/EZselection.cpp \
		src/EZtextnote.cpp \
		src/EZzic.cpp moc_EZfiledialog.cpp \
		moc_EZnotenames.cpp \
		moc_EZpiano.cpp \
		moc_EZreset.cpp \
		moc_EZscore.cpp \
		moc_EZselection.cpp
OBJECTS       = EZfiledialog.o \
		EZkey.o \
		EZnote.o \
		EZnotenames.o \
		EZnotenamesview.o \
		EZpiano.o \
		EZpianoview.o \
		EZreset.o \
		EZscore.o \
		EZscoreview.o \
		EZselection.o \
		EZtextnote.o \
		EZzic.o \
		moc_EZfiledialog.o \
		moc_EZnotenames.o \
		moc_EZpiano.o \
		moc_EZreset.o \
		moc_EZscore.o \
		moc_EZselection.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EZzik.pro
QMAKE_TARGET  = EZzik
DESTDIR       = 
TARGET        = EZzik

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EZzik.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile EZzik.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile EZzik.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EZzik1.0.0 || $(MKDIR) .tmp/EZzik1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EZzik1.0.0/ && $(COPY_FILE) --parents include/EZfiledialog.hpp include/EZkey.hpp include/EZnote.hpp include/EZnotenames.hpp include/EZnotenamesview.hpp include/EZpiano.hpp include/EZpianoview.hpp include/EZreset.hpp include/EZscore.hpp include/EZscoreview.hpp include/EZselection.hpp include/EZtextnote.hpp .tmp/EZzik1.0.0/ && $(COPY_FILE) --parents src/EZfiledialog.cpp src/EZkey.cpp src/EZnote.cpp src/EZnotenames.cpp src/EZnotenamesview.cpp src/EZpiano.cpp src/EZpianoview.cpp src/EZreset.cpp src/EZscore.cpp src/EZscoreview.cpp src/EZselection.cpp src/EZtextnote.cpp src/EZzic.cpp .tmp/EZzik1.0.0/ && (cd `dirname .tmp/EZzik1.0.0` && $(TAR) EZzik1.0.0.tar EZzik1.0.0 && $(COMPRESS) EZzik1.0.0.tar) && $(MOVE) `dirname .tmp/EZzik1.0.0`/EZzik1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EZzik1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_EZfiledialog.cpp moc_EZnotenames.cpp moc_EZpiano.cpp moc_EZreset.cpp moc_EZscore.cpp moc_EZselection.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_EZfiledialog.cpp moc_EZnotenames.cpp moc_EZpiano.cpp moc_EZreset.cpp moc_EZscore.cpp moc_EZselection.cpp
moc_EZfiledialog.cpp: include/EZselection.hpp \
		include/EZfiledialog.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZfiledialog.hpp -o moc_EZfiledialog.cpp

moc_EZnotenames.cpp: include/EZtextnote.hpp \
		include/EZnote.hpp \
		include/EZnotenames.hpp \
		include/EZnotenames.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZnotenames.hpp -o moc_EZnotenames.cpp

moc_EZpiano.cpp: include/EZkey.hpp \
		include/EZpiano.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZpiano.hpp -o moc_EZpiano.cpp

moc_EZreset.cpp: include/EZreset.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZreset.hpp -o moc_EZreset.cpp

moc_EZscore.cpp: include/EZnote.hpp \
		include/EZscore.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZscore.hpp -o moc_EZscore.cpp

moc_EZselection.cpp: include/EZselection.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZselection.hpp -o moc_EZselection.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

EZfiledialog.o: src/EZfiledialog.cpp include/EZfiledialog.hpp \
		include/EZselection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZfiledialog.o src/EZfiledialog.cpp

EZkey.o: src/EZkey.cpp include/EZkey.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZkey.o src/EZkey.cpp

EZnote.o: src/EZnote.cpp include/EZnote.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZnote.o src/EZnote.cpp

EZnotenames.o: src/EZnotenames.cpp include/EZnotenames.hpp \
		include/EZtextnote.hpp \
		include/EZnote.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZnotenames.o src/EZnotenames.cpp

EZnotenamesview.o: src/EZnotenamesview.cpp include/EZnotenamesview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZnotenamesview.o src/EZnotenamesview.cpp

EZpiano.o: src/EZpiano.cpp include/EZpiano.hpp \
		include/EZkey.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZpiano.o src/EZpiano.cpp

EZpianoview.o: src/EZpianoview.cpp include/EZpianoview.hpp \
		include/EZkey.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZpianoview.o src/EZpianoview.cpp

EZreset.o: src/EZreset.cpp include/EZreset.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZreset.o src/EZreset.cpp

EZscore.o: src/EZscore.cpp include/EZscore.hpp \
		include/EZnote.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZscore.o src/EZscore.cpp

EZscoreview.o: src/EZscoreview.cpp include/EZscoreview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZscoreview.o src/EZscoreview.cpp

EZselection.o: src/EZselection.cpp include/EZselection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZselection.o src/EZselection.cpp

EZtextnote.o: src/EZtextnote.cpp include/EZtextnote.hpp \
		include/EZnote.hpp \
		include/EZnotenames.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZtextnote.o src/EZtextnote.cpp

EZzic.o: src/EZzic.cpp include/EZpiano.hpp \
		include/EZkey.hpp \
		include/EZpianoview.hpp \
		include/EZscore.hpp \
		include/EZnote.hpp \
		include/EZscoreview.hpp \
		include/EZselection.hpp \
		include/EZfiledialog.hpp \
		include/EZtextnote.hpp \
		include/EZnotenames.hpp \
		include/EZnotenamesview.hpp \
		include/EZreset.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EZzic.o src/EZzic.cpp

moc_EZfiledialog.o: moc_EZfiledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EZfiledialog.o moc_EZfiledialog.cpp

moc_EZnotenames.o: moc_EZnotenames.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EZnotenames.o moc_EZnotenames.cpp

moc_EZpiano.o: moc_EZpiano.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EZpiano.o moc_EZpiano.cpp

moc_EZreset.o: moc_EZreset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EZreset.o moc_EZreset.cpp

moc_EZscore.o: moc_EZscore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EZscore.o moc_EZscore.cpp

moc_EZselection.o: moc_EZselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EZselection.o moc_EZselection.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

