#############################################################################
# Makefile for building: EZzik
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Mar 16 03:30:02 2016
# Project:  EZzik.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile EZzik.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -Imoc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/EZfiledialog.cpp \
		src/EZkey.cpp \
		src/EZnote.cpp \
		src/EZpiano.cpp \
		src/EZpianoview.cpp \
		src/EZscore.cpp \
		src/EZscoreview.cpp \
		src/EZselection.cpp \
		src/EZzic.cpp \
		src/EZtextnote.cpp \
		src/EZnotenames.cpp \
		src/EZnotenamesview.cpp \
		src/EZreset.cpp moc/moc_EZfiledialog.cpp \
		moc/moc_EZpiano.cpp \
		moc/moc_EZscore.cpp \
		moc/moc_EZselection.cpp \
		moc/moc_EZnotenames.cpp \
		moc/moc_EZreset.cpp
OBJECTS       = obj/EZfiledialog.o \
		obj/EZkey.o \
		obj/EZnote.o \
		obj/EZpiano.o \
		obj/EZpianoview.o \
		obj/EZscore.o \
		obj/EZscoreview.o \
		obj/EZselection.o \
		obj/EZzic.o \
		obj/EZtextnote.o \
		obj/EZnotenames.o \
		obj/EZnotenamesview.o \
		obj/EZreset.o \
		obj/moc_EZfiledialog.o \
		obj/moc_EZpiano.o \
		obj/moc_EZscore.o \
		obj/moc_EZselection.o \
		obj/moc_EZnotenames.o \
		obj/moc_EZreset.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EZzik.pro
QMAKE_TARGET  = EZzik
DESTDIR       = 
TARGET        = EZzik

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EZzik.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile EZzik.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile EZzik.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/EZzik1.0.0 || $(MKDIR) obj/EZzik1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/EZzik1.0.0/ && $(COPY_FILE) --parents include/EZfiledialog.hpp include/EZkey.hpp include/EZnote.hpp include/EZpiano.hpp include/EZpianoview.hpp include/EZscore.hpp include/EZscoreview.hpp include/EZselection.hpp include/EZtextnote.hpp include/EZnotenames.hpp include/EZnotenamesview.hpp include/EZreset.hpp obj/EZzik1.0.0/ && $(COPY_FILE) --parents src/EZfiledialog.cpp src/EZkey.cpp src/EZnote.cpp src/EZpiano.cpp src/EZpianoview.cpp src/EZscore.cpp src/EZscoreview.cpp src/EZselection.cpp src/EZzic.cpp src/EZtextnote.cpp src/EZnotenames.cpp src/EZnotenamesview.cpp src/EZreset.cpp obj/EZzik1.0.0/ && (cd `dirname obj/EZzik1.0.0` && $(TAR) EZzik1.0.0.tar EZzik1.0.0 && $(COMPRESS) EZzik1.0.0.tar) && $(MOVE) `dirname obj/EZzik1.0.0`/EZzik1.0.0.tar.gz . && $(DEL_FILE) -r obj/EZzik1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_EZfiledialog.cpp moc/moc_EZpiano.cpp moc/moc_EZscore.cpp moc/moc_EZselection.cpp moc/moc_EZnotenames.cpp moc/moc_EZreset.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_EZfiledialog.cpp moc/moc_EZpiano.cpp moc/moc_EZscore.cpp moc/moc_EZselection.cpp moc/moc_EZnotenames.cpp moc/moc_EZreset.cpp
moc/moc_EZfiledialog.cpp: include/EZselection.hpp \
		include/EZfiledialog.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZfiledialog.hpp -o moc/moc_EZfiledialog.cpp

moc/moc_EZpiano.cpp: include/EZkey.hpp \
		include/EZpiano.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZpiano.hpp -o moc/moc_EZpiano.cpp

moc/moc_EZscore.cpp: include/EZnote.hpp \
		include/EZscore.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZscore.hpp -o moc/moc_EZscore.cpp

moc/moc_EZselection.cpp: include/EZselection.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZselection.hpp -o moc/moc_EZselection.cpp

moc/moc_EZnotenames.cpp: include/EZtextnote.hpp \
		include/EZnote.hpp \
		include/EZnotenames.hpp \
		include/EZnotenames.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZnotenames.hpp -o moc/moc_EZnotenames.cpp

moc/moc_EZreset.cpp: include/EZreset.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/EZreset.hpp -o moc/moc_EZreset.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/EZfiledialog.o: src/EZfiledialog.cpp include/EZfiledialog.hpp \
		include/EZselection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZfiledialog.o src/EZfiledialog.cpp

obj/EZkey.o: src/EZkey.cpp include/EZkey.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZkey.o src/EZkey.cpp

obj/EZnote.o: src/EZnote.cpp include/EZnote.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZnote.o src/EZnote.cpp

obj/EZpiano.o: src/EZpiano.cpp include/EZpiano.hpp \
		include/EZkey.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZpiano.o src/EZpiano.cpp

obj/EZpianoview.o: src/EZpianoview.cpp include/EZpianoview.hpp \
		include/EZkey.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZpianoview.o src/EZpianoview.cpp

obj/EZscore.o: src/EZscore.cpp include/EZscore.hpp \
		include/EZnote.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZscore.o src/EZscore.cpp

obj/EZscoreview.o: src/EZscoreview.cpp include/EZscoreview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZscoreview.o src/EZscoreview.cpp

obj/EZselection.o: src/EZselection.cpp include/EZselection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZselection.o src/EZselection.cpp

obj/EZzic.o: src/EZzic.cpp include/EZpiano.hpp \
		include/EZkey.hpp \
		include/EZpianoview.hpp \
		include/EZscore.hpp \
		include/EZnote.hpp \
		include/EZscoreview.hpp \
		include/EZselection.hpp \
		include/EZfiledialog.hpp \
		include/EZtextnote.hpp \
		include/EZnotenames.hpp \
		include/EZnotenamesview.hpp \
		include/EZreset.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZzic.o src/EZzic.cpp

obj/EZtextnote.o: src/EZtextnote.cpp include/EZtextnote.hpp \
		include/EZnote.hpp \
		include/EZnotenames.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZtextnote.o src/EZtextnote.cpp

obj/EZnotenames.o: src/EZnotenames.cpp include/EZnotenames.hpp \
		include/EZtextnote.hpp \
		include/EZnote.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZnotenames.o src/EZnotenames.cpp

obj/EZnotenamesview.o: src/EZnotenamesview.cpp include/EZnotenamesview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZnotenamesview.o src/EZnotenamesview.cpp

obj/EZreset.o: src/EZreset.cpp include/EZreset.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EZreset.o src/EZreset.cpp

obj/moc_EZfiledialog.o: moc/moc_EZfiledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EZfiledialog.o moc/moc_EZfiledialog.cpp

obj/moc_EZpiano.o: moc/moc_EZpiano.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EZpiano.o moc/moc_EZpiano.cpp

obj/moc_EZscore.o: moc/moc_EZscore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EZscore.o moc/moc_EZscore.cpp

obj/moc_EZselection.o: moc/moc_EZselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EZselection.o moc/moc_EZselection.cpp

obj/moc_EZnotenames.o: moc/moc_EZnotenames.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EZnotenames.o moc/moc_EZnotenames.cpp

obj/moc_EZreset.o: moc/moc_EZreset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_EZreset.o moc/moc_EZreset.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

